package tui

const (
	KeyQuit        = "ctrl+c"
	KeyQuitAlt     = "q"
	KeyUp          = "up"
	KeyUpAlt       = "k"
	KeyDown        = "down"
	KeyDownAlt     = "j"
	KeyEnter       = "enter"
	KeySpace       = " "
	KeyNext        = "n"
	KeyPrev        = "p"
	KeyHelp        = "?"
	KeyRetry       = "r"
	KeyLogout      = "L"
	KeyVolumeDown  = "-"
	KeyVolumeUp    = "+"
	KeyAutoplay    = "a"
	KeyShuffle     = "s"
	KeySeekBack    = "h"
	KeySeekForward = "l"
	KeySearch      = "/"
	KeySearchNext  = "]"
	KeySearchPrev  = "["
)
